name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite rodar manualmente
  
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Animação da cobrinha
      - uses: Platane/snk@v3
        with:
          # nome do usuario github
          github_user_name: FelipeDev2020
          # arquivos de saida (o svg normal e o dark mode)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Empurra os arquivos gerados para a branch output
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
